### ISSUE TITLE
How start?

### ISSUE THREAD

**Issue by srem1** [yoshoku/llama_cpp.rb#1]
How install models and how using it to make a simple chat or whatewer?

**Comment by yoshoku** [comment]
@srem1 
llama_cpp.rb is a thin Ruby bindings for the llama.cpp, and that purpose is to provide low-level APIs. Like an example program of llama.cpp ( https://github.com/ggerganov/llama.cpp/tree/master/examples/main ), you can reate a chat system using those APIs. I am also planning to implement high-level APIs ( https://yoshoku.github.io/llama_cpp.rb/doc/LLaMACpp/Client.html ), but the development of llama.cpp is so fast that I am barely catching up. 
Please refer to the llama.cpp README to download and quantize a model yourself ( https://github.com/ggerganov/llama.cpp#prepare-data--run ). I would not provide a direct link to the models, as it might be a violation of the license, for example,  skipping the agreement to the terms of use. Thank you for your understanding in advance.
