### ISSUE TITLE
ASCII-8bit instead of UTF

### ISSUE THREAD

**Issue by simon-dedeo** [yoshoku/llama_cpp.rb#13]
I notice that the output of token_to_piece is ASCII-8bit:

```
irb(main):167:0> context.model.token_to_piece(10).encoding
=> #<Encoding:ASCII-8BIT>

```

It is certainly easy to run `.encode('UTF-8', invalid: :replace, undef: :replace, replace: "")` but perhaps this is unsafe. Is there a reason we get ASCII-8BIT out, and what's the best way to handle this (my understanding is that LLMs are generally trained on UTF.)

**Comment by yoshoku** [comment]
The `token_to_piece` method has been changed to return a UTF-8 String from v0.7.0. Please try it.
https://github.com/yoshoku/llama_cpp.rb/commit/db838d80c8f2efc61079140457bad56b93f8fd2d

**Comment by simon-dedeo** [comment]
Thank you, yoshoku; your fixes install just fine on my Mac M1, and it's now returning UTF as expected.
