### ISSUE TITLE
Default to using --with-metal on macOS

### ISSUE THREAD

**Issue by technicalpickles** [yoshoku/llama_cpp.rb#5]
I think enabling this will make for a better experience for folks on macos. Otherwise, you'd have to know to reinstlal with `--with-metal` and/or run `bundle config build.llama_cpp -- --with-metal`.

Let me know if should file this on https://github.com/ggerganov/llama.cpp if that makes more sense

cc https://github.com/yoshoku/llama_cpp.rb/issues/3 where it was initially requested.

**Comment by yoshoku** [comment]
@technicalpickles 
llama.cpp has a fast development speed, and it can be difficult to provide a gem that can be built stably. Currently, I value being able to install without adding any options. Once llama.cpp's build options and API become stable, I would like to consider implementing automatic optimal option selection.

**Comment by technicalpickles** [comment]
Would you say it would be better to get that behavior into llama.cpp instead?

**Comment by yoshoku** [comment]
From ver. 0.11.0, llama_cpp gem uses the Makefile of llama.cpp to create the library and link it. As a result, the llama_cpp gem defaults to using metal on macOS.
